name: Publish
on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@master
      - name: Install Node.js and yarn
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - name: Install Modules
        run: yarn
      - name: Test
        run: yarn build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: eu-west-2
      - name: Copy files to the production website with the AWS CLI
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET }} --delete --acl public-read
