name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and yarn
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn

      - name: Install Modules
        run: yarn

      - name: Test
        run: yarn test
